version: "3.9"

services:
  app3:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8007:8007"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate  && python manage.py runserver 0.0.0.0:3000"
    env_file:
      - .env
