version: '3.10'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      # - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./init-scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  web:
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8000"
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env